#include "dictionary.h"
static HashNode0 hashnode0[SUM_OF_KEY_CHAR];
#define SUM_OF_DICTIONARY_WORDS 3457
#define SUM_OF_SIMILAR_GROUP 10
static string myDearWords[] = { 
	"zoology","zoo","zero","yourself","yours","your","young","you","yoga","yield","yet","yesterday","yes","yellow","yard","wrong","writer","write","wreck","wrap","worship","worry","worried","world","workshop","workout","workforce","work","wooden","wood","wonderful","wonder","woman","withstand","without","with","wit","wish","wireless","winter","winner","wine","windy","window","wind","willpower","will","wilderness","wild","widespread","wide","why","whose","whom","who","white","whiskey","whip","while","whereby","whereas","where","whenever","wheel","whatsoever","whatever","what","wet","western","west","well","welfare","welcome","weird","weigh","weekend","weekday","weave","weather","wear","weaponry","weapon","weak","we","way","wavy","watertight","waterproof","watermelon","water","watchful","watch","waste","wash","was","wary","warrior","warm","warfare","ware","want","wall","walk","wake","waitress","waiter","wait","wagon","vulnerable","volunteer","voluntary","voluminous","volume","volt","volleyball","vocation","vitamin","visual","visitor","visit","vision","visible","virtual","violin","violate","village","vigour","vigorous","viewpoint","view","video","via","veto","veteran","vessel","very","versus","version","verify","verbal","verb","venture","vendor","veil","vehicle","vegetarian","vegetable","vary","vapour","vanity","vanish","van","valid","vacuum","vacation","vacancy","utter","utmost","utilize","utility","usually","use","usage","us","upright","upload","upgrade","up","until","unpleasant","unless","university","unique","unify","uniform","unhappy","unfriendly","unfair","undo","undertake","undermine","underlie","underground","undergraduate","undergo","underestimate","under","uncomfortable","uncle","umbrella","ultimate","ugly","type","two","twice","twenty","twentieth","twelve","twelfth","tutorial","turn","tunnel","tumour","tuition","try","trustee","trolley","triumphant","triumph","triple","trip","trigger","trifle","trend","tremendous","tree","treaty","treat","tray","travel","trash","transportation","transport","transplant","transparency","transmit","translate","transition","transit","transform","transfer","transcript","transact","training","train","trailer","trail","tragic","tragedy","traffic",
	"traditional","tradition","trademark","trace","toy","township","town","tower","towel","toward","tourist","tour","touchy","toss","torture","torch","topic","top","toothbrush","toothache","tooth","tool","too","tonight","tone","tomorrow","tomato","toll","token","together","toe","today","toast","to","tiring","tired","tiny","time","timber","till","tiger","tie","tide","ticket","thumb","thrust","throw","through","throat","thrive","three","threat","thousands","thousand","thought","though","those","this","thirty","thirtieth","thirteenth","thirteen","third","think","thing","thin","they","thesis","these","thermometer","thereby","there","therapy","theory","then","themselves","theme","the","that","thank","than","textile","text","test","territory","terrific","terminate","term","tenth","tense","tennis","tender","ten","temporary","temperature","temper","teller","tell","telephone","telecommunication","teeth","teenager","teen","tedious","technology","technique","technician","technical","team","teacher","teach","tea","taxi","taste","task","target","tape","tangible","tame","tall","talk","take","tag","tackle","table","sympathise","symbol","swipe","swim","sweet","sweep","sweater","sway","sustain","suspicious","suspicion","suspense","suspend","survive","survey","surrender","surprised","surprise","surname","surgical","surgery","surge","surf","sure","supremacy","supposition","suppose","support","supplement","supervise","supermarket","superficial","super","sunset","sunrise","sunny","sunglasses","summit","summer","summary","sum","suitcase","suitable","suit","suggestion","sufficient","such","successor","successful","success","succeed","subway","suburb","subtract","substitute","substance","subsidy","subsequent","subordinate","submit","submissive","subject","style","stuffy","stuff","study","student","structure","stroke","strive","stripe","strip","stride","strict","stretch","stress","street","strawberry","strategy","strap","strange","strain","straightforward",
	"stormy","storey","stool","stomachache","stock","stir","sting","stimulus","stimulate","stimulant","stiff","stem","steer","steamer","status","statistic","stationary","startle","standpoint","stale","stake","staircase","stack","stable","spur","spring","spouse","sportsman","spontaneous","spoil","splendour","splash","spite","spill","sphere","speculate","specimen","specify","specific","species","spatial","sparkle","spark","span","spaghetti","spacecraft","space","southeast","source","sore","sophistication","sophisticated","somewhere","somewhat","sometimes","something","solvent","solve","solution","soluble","solemn","sole","soda","sock","sociology","socialise","sociable","soccer","soar","soak","so","snow","snake","snack","smell","smash","smart","small","slowly","slow","slope","slogan","slippery","slipper","slice","slender","sleepy","sleep","slap","skyline","sky","skirt","skinny","skin","skill","sketchy","sketch","skeleton","skateboard","skate","size","sixty","sixth","sixteenth","sixteen","six","situation","site","sit","sister","sir","singular","single","singer","sing","sincerely","since","sin","simulate","simple","similar","silly","silicon","significant","sign","sightseeing","sight","siege","sick","shy","shrug","shrimp","showy","shower","show","shout","should","short","shop","shoe","shiver","shit","shirt","shift","shell","shelf","sheer","shed","she","shape","shake","sex","several","seventy","seventh","seventeenth","seventeen","seven","setback","service","serve","serious","series","sequence","sentence","sensor","sensible","send","senator","senate","semi","semester","sell","select","seizure","segment","seem","seek","see","secure","sector","section","secret","second","season","sea","scripture","script","screw","screen","scout","scope","scoop","scientist","scientific","science","school","scheme","schedule","scent","scene","scenario","scatter","scarf","scarce","scandal","scale","saying","say","save","sauce","sane","sandwich","sample","same","salt","sale","salad","sake","saint","safe","sad","sack","rush","rural","runway","run","rumour","rule","rug","rude","rubbish","rub","route","rouse","rose","room","roof","romantic","role","rod","rocket","rock","robot","roar","river","rival","risk","rise","rip","riot","ring",
	"rigid","right","rifle","ridicule","ride","rich","rice","ribbon","rib","rhythm","revolve","revolution","revise","review","reverse","revenue","reveal","reunion","return","retreat","retention","retain","retail","resume","result","restrict","restrain","restore","rest","response","respond","respective","resource","resort","resolve","resolution","reside","resent","research","require","reproductive","reproduce","reporter","report","repetitive","repay","repair","rent","renovate","render","remove","remember","remedy","remain","rely","reluctance","relieve","relevant","release","relaxed","relax","relativity","reject","reinforce","regulate","registrar","register","region","regime","regard","refuse","refrain","refine","reduce","red","recycle","recruit","recover","record","reckon","recipient","recession","receptive","recently","recent","receive","recall","rebel","reason","rear","reap","realm","really","realize","read","react","rational","ratio","range","random","rally","raise","rainy","raincoat","rain","raid","ragged","rage","radio","radical","radar","rack","race","quote","quota","quite","quiet","quickly","quick","question","quarter","quantify","qualitative","put","push","pursuit","pursue","purse","purpose","purple","purify","purchase","punch","pull","publish","publicize","publication","public","psychology","provoke","provision","province","provide","proverb","proud","protocol","protest","protein","prospect","prose","proposition","propose","proportion","property","proper","proof","pronunciation","pronounce","prompt","promote","prominent","prominence","projector","project","prohibit","progress","program","profound","proficient","professional","produce","proclaim","procession","process","proceed","problem","probably","prize","privatise","priority","prior","principle","principal","princess","prince","prime","primary","priest","price","previous","prevalent","prevail","pretty","presume","pressure","press","presidency","present","preliminary","prefer","preface",
	"predominant","predict","precise","precede","precaution","preach","practitioner","practice","poverty","pour","pound","potential","potato","posture","poster","postcard","possible","positive","pose","portion","porridge","populous","population","popular","poor","pool","pollution","pollute","pollster","poll","polite","policy","policewoman","policeman","police","polar","point","poem","plus","plural","plunge","plough","plenty","pledge","pleasure","pleased","please","pleasant","player","play","plastic","plantation","plant","planet","plane","plan","plague","place","pizza","pity","pitch","pit","pistol","pirate","piracy","pink","pinch","pilot","pillar","pigeon","pig","pierce","piece","pie","picturesque","picture","picnic","pick","piano","physics","physical","phrase","photograph","photo","phone","philosophy","phenomenon","phase","petty","petroleum","pet","pessimistic","pessimist","pessimism","perspective","personality","personal","persist","persevere","permissive","period","peril","perhaps","perform","perfect","perceptive","percent","perceive","people","penetrate","pencil","penalty","penalise","pen","peer","peculiar","peasantry","peasant","pearl","pear","peanut","peak","peaceful","peace","payroll","pay","paw","patient","patch","pat","pastime","paste","past","password","passive","passion","passenger","pass","party","partner","particle","participate","part","parrot","parliament","park","parents","parent","parameter","parallel","paragraph","paradox","paradigm","parade","paperback","paper","pants","panel","panda","pancake","palm","palace","pair","paint","paddy","pad","pack","ozone","owner","own","overwhelm","overtime","overthrow","overtake","oversight","oversee","overseas","overnight","overlap","overhear","overdue","overall","over","oven","outskirts","outside","outset","output","outlook","outlet","outdoor","outdated","outcome","out","ourselves","ours","our","ounce","other","orphanage","orphan","ornament","orient","organize","organization","organism","organic","ore","order","orchestra","orange","or","option","optimism","opt","opposite","opportunity","opponent","opinion","open","onwards","only","online","onion","ongoing","one","once","on","omit","old","okay","oh","often","offset","officer","office",
	"offer","offend","off","of","odour","odd","ocean","occur","occupy","occasion","obvious","obtain","obstacle","oblige","objective","obey","obese","nurse","numerous",
	"number","nuisance","nude","nucleus","nuclear","now","novelty","nourish","noun","notwithstanding","notional","notion","notify","notification","notice","nothing","notebook","note","notate","not","nosy","nose","northern","north","normally","normal","norm","noodle","nonsense","nonetheless","noise","nobody","no","ninth","nineteenth","nineteen","nine","nightmare","night","nickel","nicety","nice","next","newspaper","news","new","nevertheless","never","neutral","network","net","nervous","nerve","neither","neighbor","negotiable","neglect","negative","negate","needy","need","neck","necessity","necessitate","necessary","nearly","nearby","near","naval","naughty","nature","natural","nation","nasty","narrate","napkin","nap","name","naked","mythology","mythic","myth","mystery","myself","my","mutual","must","musician","musical","music","museum","muscular","muscle","murder","municipal","multiple","mule","mug","much","movie","move","mouth","mouse","mountain","mount","mould","motorway","motive","motion","mother","motel","mostly","most","mortgage","morning","moreover","more","moon","mood","month","monster","monkey","monitor","money","monetary","moment","mom","moist","modify","modern","moderate","model","mode","mix","mistake","mission","miss","misfortune","miserable","miraculous","miracle","minute","minor","ministry","minimum","minimize","minimal","miner","mine","mind","million","mill","milk","military","mile","migrate","migrant","mighty","middle","microphone","metro","method","meter","messenger","message","mess","meritorious","merit","menu","mention","mental","mend","memorandum","memo","member","melt","meeting","meet","medium","medicine","medical","mediate","media","medal","mechanism","mechanise","mechanic","meat","measure","meantime","mean","meal","me","mayor","maybe","may",
	"maximize","maximal","mature","matter","math","material","mate","match","masterpiece","massive","massage","marvel","marshal","marsh","market","mark","marital","marine","margin","map","many","manufacture","manual","manipulate","man","mammal","mall","makeup","make","major","maintain","mainstream","mainly","main","mail","magnificent","magnet","magic","magazine","made","madam","mad","luxury","lunch","lunar","lump","lucky","luckily","loyal","low","lovely","love","loudly","loud","lots","lot","lost","lose","lord","loophole","look","long","logo","logic","log","lodge","locker","lock","locate","locality","local","lobby","loan","living","liver","lively","livelihood","live","little","litter","literal","literacy","listen","list","liquor","lion","link","linear","line","limb","lily","likewise","like","light","life","lie","lick","license","library","liberal","liable","levy","lettuce","letter","let","lest","lesson","less","lens","lend","leisure","legislate","legal","leg","left","lecture","leave","least","lease","learn","leap","lean","leaf","leader","lead","lazy","layout","layoff","layer","lay","lawn","lavatory","launch","laugh","later","late","last","laser","large","laptop","lap","language","lane","landscape","landlord","landlady","land","lag","lady","ladder","lace","laboratory","labor","label","kung","know","knot","knock","knit","knife","kneel","knee","kite","kitchen","kit","king","kind","kin","kilometer","kill","kid","key","keep","keen","justify","just","jury","juror","junk","jump","juice","journal","joke","joint","join","job","jetlag","jeans","jealous","jazz","jail","item","it","issue","isolate","island","is","irony","inward","involve","invoke","invite","invitation","investigate","invest","invent","invasive","invasion","invade","intrusion","intrude","intrinsic","into","intimate","interview","intervene","interval","interpret","international","internal","intermediate","interior","interfere","interesting","interested","interest","interact","intense","intelligent","intellectual","integrity","integrate","integral","intake","intact","insult","instrument","instruct","institute","instinct","instead","instance","instalment","install","inspect","insight","insert","insect","inquire","input","innovate","inland","injure","initiate",
	"initial","inhibit","inherit","inherent","inhabitant","inhabit","ingredient","infrastructure","information","influence","inflate","infinity","infinite","inferior",
	"infer","infect","infant","inevitable","industrious","induce","individual","indispensable","indifferent","indifference","indicate","index","incredible","increase","incorporate","income","including","include","incline","incidental","incidence","incentive","in","impulse","improve","impossible","impose","important","importance","impolite","imply","implicit","implicate","implement","imperial","impatient","impatience","impact","immune","immigrate","immigrant","immense","imitate","imagine","image","illustrate","illusory","illusion","illness","ill","ignorant","if","idle","ideology","identify","identical","idealistic","ideal","idea","ice","hypothesis","hyphen","hut","husband","hurt","hundred","humble","human","huge","however","how","housework","household","house","hour","hotel","hot","hostile","host","hospitality","hospital","hospitable","horsepower","horror","horrifying","horn","horizontal","horizon","hope","honeymoon","honey","honest","homework","hometown","homeless","home","hollow","holiday","hold","hobby","hit","history","his","hip","hint","hinder","himself","hijack","highlight","high","hierarchy","hi","hey","hesitant","herself","hers","heroine","hero","heritage","hereby","here","herd","her","hence","hen","helpful","help","hello","hell","heir","heighten","height","hedge","hectare","heavy","heat","hearty","heart","heap","healthy","health","heal","headquarters","headmistress","headache","head","he","hazy","haze","hazard","hay","have","haunt","haul","hate","hat","haste","has","harsh","harness","hardware","hardly","hard","happy","happen","hang","handicap","handbook","hand","hamburger","halt","hall","haircut","hair","hail","hack","habitat","habit","ha","gym","guy","gut","gum","gulf","guitar","guideline","guidebook","guide","guardian","guarantee","grow","group","gross","grip","grind","grin","grievous","grieve","grief","greet","greenhouse","green","great","gray","grave","gratitude","grass","graphic","grant","grandson","grandparent","grandmother","grandfather","grammatical","grammar","graduate","grade","gracious","grace","grab","gown","government","gossip","gorgeous","goose","goodbye","good","gold","goal","go","glow","gloom","globe","glimpse","glasses","give","girl","gigantic","gift","giant","ghost","get","germ","geology","geological","geography",
	"genuine","gentle","genius","genetic","generator","generation","generate","general","gene","gender","gear","gaze","gas","garden","garbage","garage","gap","gaol","gangster","gang","game","gamble","gallery","gadget","future","fuss","furthermore","furnace","funny","fundamental","fund","function","fun","full","fulfil","fuck","frustrate","fruitful","fruit","front","from","friendship","friend","freshman","fresh","freight","free","frank","framework","frame","fragment","fraction","fox","fourth","fourteenth","fourteen","four","foundation","found","fossil","forum","forty","forthcoming","forth","formula","format","formal","form","fork","forget","forge","forestry","foresight","foreigner","foreign","fore","forbid","for","footprint","football","foot","food","following","follow","focus","fly","fluid","fluctuate","flower","flourish","floor","flock","flight","flexible","fleet","flaw","flavour","flag","fixture","fixate","fix","five","fit","fisherman","fish","firstly","first","fireplace","fireman","finite","finish","fingerprint","finger","find","finance","finally","final","filter","film","fill","file","figurative","fight","fifty","fifth","fifteenth","fifteen","few","fever","fetch","festival","fertile","feel","feedback","feed","fee","federate","federal","feature","feasible","fear","fax","favorite","fatigue","father","fate","fatal","fat","fast","fashionable","fashion","fascinate","farmer","farm","farewell","far","fantastic","fan","famous","famine","family","fall","fake","fairy","fair","faint","fail","faculty","factory","factor","fact","facility","facilitate","face","fabric","fable","eyebrow","eye","extract","extinguish","external","exterior","expressway","expression","expose","export","explosion","explorer","exploit","explicit","explain","expert","experiment","experience","expensive","expend","expel","expect","expansion","expanse","expand","exile","exhibition","exhibit","exhaustive","exhaustion","exhaust","exert","exercise","exemplify","exemplar","executive","execute","excuse","excursion","exclude","exclaim","exciting","excited","exchange","excess","except","excellent",
	"excel","exceed","exam","exaggerate","exactly","evolve","evil","evident","everywhere","everything","everyone","every","ever","eventual","evening","even","eve","evaluate","euro","ethnic","ethic","eternity","eternal","estimate","estate","establish","essential","essence","especially","escape","error","erroneous","err","erode","eraser","era","equivalent","equipment","equip","equate","episode","environment","envelope","entrepreneurial","entrepreneur","entity","entitle","enter","ensure","enrol","enrich","enough","enormous","enlighten","enjoy","enhance","engage","enforce","energy","endure","endurance","end","encourage","encounter","enable","empty","empress","empirical","empire","emphatic","emphasis","emperor","emotion","emit","emerge","embrace","else","elite","eliminate","eleventh","eleven","elevate","elephant","elementary","element","elegance","electron","electric","elective","elbow","either","eighty","eightieth","eighth","eighteenth","eighteen","eight","egg","efficient","educational","edit","economy","ecological","echo","eat","easy","eastern","easily","ease","earnest","early","ear","each","dynamic","dye","duty","during","duration","durable","dumpling","dump","dumb","duck","dual","drunken","drunkard","drum","drown","drought","dropout","drop","drive","drip","drink","drift","dress","dream","drawer","draw","drastic","drama","drainage","drain","dragon","draft","downstairs","down","dose","dormitory","door","doom","donor","donkey","dominate","domestic","domain","dolphin","dollar","dog","does","documentary","document","doctorate","doctor","dock","do","divisive","divide","diversify","diverse","ditch","distribute","distress","distract","distort","distinct","distance","dissolve","disruptive","disrupt","dispute","dispose","display","displace","disorder","dislike","disintegrate","disguise","discussion","discuss","discriminate","discrete","discover","disco","discipline","discharge","discard","disapprove","disappear","diplomat","diplomacy","dine","diminish","dimension","dime","dim","diligent","dignify","digit","differentiate","diameter","dialect","diagnosis","diagnose","diabetes","dew",
	"devote","devise","devil","device","deviate","deteriorate","detect","detail","despite","despair","desktop","design","descent","descend","derive","deputy","depress",
	"depart","deny","dental","dent","dense","denote","demonstrate","democrat","democracy","deliberated","delegate","defy","definite","define","deficit","deficiency","defiant","defiance","defendant","defected","defect","deem","deduce","decline","deck","decisive","deception","decent","deceive","deceit","decay","decade","debate","dean","date","data","darling","damn","dairy","cycle","cute","cut","custom","curve","curse","curry","current","currency","curly","curl","curb","cup","culture","cultivate","cue","cucumber","crystal","crush","cruise","crucial","crown","crowded","crowd","cross","crocodile","criticism","criticise","critic","criteria","crisis","creep","creditable","credit","create","crazy","craze","crawl","crane","craft","cracker","crack","crab","cowboy","coward","cow","cover","cousin","court","course","coupon","couple","county","countryside","country","counterpart","countdown","count","counsel","council","could","cough","couch","costume","cost","cosmos","cosmic","corridor","correspondent","correspond","corps","corporate","cornerstone","corner","core","cord","copyright","copy","copper","cope","cop","coordinate","cooperate","cool","cookie","cook","convince","convert","converse","conversation","convene","controversy","contribute","contrast","contrary","contradict","contraction","contract","continue","context","contest","contentious","contend","contempt","contemporary","contaminate","contact","consume","consult","construct","constrain","constitute","constant","consolidate","consist","considerable","consider","consequent","consent","conscientious","conquest","conquer","conjunction","congress","confront","conform","conflict","confirm","confine","confident","confess","confer","conduct",
	"condense","concurrent","conclusion","conclude","concerted","concert","concept","concentrate","conceive","conceal","comrade","computer","compute","comprise","comprehensive","compound","component","comply","complicate","compliance","complex","complete","complement","complaint","complain","compile","competition","competent","compensate","compel","compatible","compare","company","commute","community","communicate","commune","commonplace","common","commodity","commit","commission","comment","commence","comma","comfortable","comedy","come","combat","columnist","column","color","colony","colon","collection","collect","colleague","collapse","collaborate","cold","coincide","coin","coil","cohesion","coherent","coffee","code","cock","coarse","coach","clue","club","clown","cloudy","clothing","close","clockwise","clock","clip","cling","climb","climax","cliff","client","clever","clerk","clerical","clearly","clean","clause","classroom","classmate","classic","class","clash","clarify","claim","civil","city","cite","circumstance","circle","cinema","church","chore","chop","choose","cholesterol","chocolate","chip","chin","chimney","chill","children","chicken","chess","cherish","chemistry","chemical","cheer","check","cheap","chat","chase","charter","chart","charm","charity","charitable","character","chapter","chaotic","channel","chance","champion","champagne","challenge","chairperson","chair","certainly","certain","cereal","century","center","cement","cellar","cease","cause","category","catch","cat","cashier","cart","carry","carrot","cargo","careful","career","care","cardboard","card","car","capture","capitalist","capitalism","capita","capacity","capable","cane","candy","can","campus","camp","camera","camel","came","calorie","calm","call","calf","calendar","cake","cage","cable","cabinet","cabin","cabbage","bystander","bypass","by","buy","butter","but","busy","business","bus","burn","bureau","bundle","bump","bully","bulletin","bullet","bull","bulk","bulb","building","build","bug","buddy","bud","buckle","bucket","buck","bubble","brute","brush","browse","brown","brow","brother","broker","bring","brilliance","bright",
	"briefcase","brief","bridge","bribe","breeze","breed","breakfast","breakdown","break","breadth","bread","brave","brass","brandy","brag","bracket","boy","box","bowl","bowel","both","borrow","born","boring","bored","boost","boomer","bookcase","book","bondage","bond","bolt","bold","boil","body","boat","boast","blur","blueprint","blue","blossom","bloom","blonde","blind","blend","blast","blade","black","bitch","bit","biscuit","birthday","birth","bird","biotechnology","biology","biographer","biochemist","biochemical","bin","billionaire","bike","big","bicycle","bias","beverage","between","better","bet","best","besides","beside","berry","benefit","bench","belt","beloved","bell","behind","behavior","behave","behalf","beginning","begin","beforehand","before","beef","bedroom","bed","become","because","beautiful","beat","beam","beach","be","battalion","bathroom","batch","basketball","basket","barrel","bark","banquet","banner","bankruptcy","bankrupt","banknote","bank","bang","band","banana","ballot","ball","balance","bait","bail","bag","badge","bad","backyard","backup","backpack","back","babysit","baby","axis","axe","awe","away","aware","award","awake","await","aviation","avenue","available","autumn","automobile","automate","authority","authorise","author","aunt","auditorium","audio","attribute","attorney","attitude","attic","attentive","attention","attain","attach","atop","athlete","at","astronomical","assure","assume","assist","assign","asset","assess","assemble","ass","aspect","asleep","ask","ashore","as","artist","art","arrive","arouse","around","armament","arm","argumentative","argue","area","are","arbitrary","aptitude","approximate","appropriate","approach","appreciate","appointment","appliance","apple","applause","append","appear","apparent","apparatus","apartment","anywhere","anyway","anything","anyone","any","anxious","anticipate","ant","answer","another","annual","animal","angry","angel","anew","and","ancient","ancestry","analyze","analogy","an","amusement","amidst","amid","amend","ambitious","ambiguous","am","always","although","alternative","alter","also","already","aloud","alone","ally","allow","allocate","alliance","allege","all","alive","alien","alert","albeit","aisle","airport","airplane","aim",
	"aid","agree","ago","aggression","aggregate","age","against","again","afternoon","after","afraid","afford","affluent","affluence","affect","aeroplane","aerial","advocate","advocacy","advice","advertisement","adverb","advantage","adult","administer","adjust","adjective","adjacent","adequate","address","add","adapt","actor","activity","active","action","act","across","acquire","acknowledge","achieve","ace","accurate","accumulate","accountable","according","accord","accompany","accommodate","accident","access","academy","abundance","abstract","about","abolition","able","abandon","a","ZnSO4","ZnCl2","Zn(NO3)2","Zn","Yankee","Wednesday","WO3","W","V2O5","V","UFO","Tuesday","Toronto","Tibet","Thursday","Thanksgiving","Thailand","TRUE","Sydney","Sunday","Straight","Story","Store","Stop","Stone","Stomach","Still","Stick","Step","Stay","Station","Start","Star","Stand","Stamp","Stage","Square","Sport","Spoon","Spoken","Spend","Spell","Speech","Special","Speak","Spare","Spain","Southern","South","Sour","Soup","Sound","Sorry","Sore","Soon","Song","Son","Someone","Some","Solve","Sofa","SiO2","SiF4","Si3N4","Si","September","Saturday","San","SO3","SO2","S8","S","Russian","Russia","Pt","PbS","PbN6","PbCrO4","PbBr2","Pb3O4","Paris","PI3","PH4I","PCl5","PCl3","P4","P2O5","P2I4","P","Olympic","Olympiad","October","OK","O3","O2","November","NiCl2","NaOH","NaNO3","NaNO2","NaMnO4","NaHSO4","NaHSO3","NaHS","NaHCO3","NaH","NaCr(OH)4","NaClO","NaCl","NaBr","NaBiO3","NaAlO2","NaAlF4","Na4(B10H10CNH2)2Ni","Na2SiO3","Na2SO4","Na2SO3","Na2S5","Na2S","Na2O2","Na2O","Na2CrO4","Na2CO3","Na","NO2","NO","NH4NO3","NH4HCO3","NH4Cl","NH3","N2O4","N2","Ms","Mr","Monday","MnSO4","MnO2","MnO","MnCl2","Mn","Miss","MgSiO3","MgSO4","MgO","MgH2","MgCl2","MgCO3","Mg3N2","Mg(OH)2","Mg(NO3)2","Mg(HCO3)2","Mg","May","Marx","Mars","March","Los","LiOH","LiH","Li2O","Li","KOH","KOCN","KO2","KNO3","KMnO4","KI","KHSO4","KH","KF","KClO3","KCl","KBr","KAl(SO4)2","KAl(OH)4","K4Fe(CN)6","K2SO4","K2S","K2NaCo(NO2)6","K2MnO4","K2Cr2O7","K","June","July","Jewish","Japanese","Japan","January","Italy","Internet","Indian","ID",
	"I2","I","Hong","HgO","Hg(NO3)2","Hg","Halloween","HPO3","HNO3","HI","HF","HClO","HCl","HCOOH","HCHO","HBr","H4SiO4","H3PO4","H3PO2","H2SiO3","H2SO4","H2SO3","H2S","H2PtCl6","H2O2","H2O","H2CO3","H2","Greece","GeO2","GeHPO3","Friday","French","France","February","FeSO4","FeS2","FeS","FeO","FeCl3","FeCl2","Fe3O4","Fe3C","Fe2O3","Fe2(SO4)3","Fe(SCN)3","Fe(OH)3","Fe(OH)2","Fe(NO3)3","Fe(NO3)2","Fe","F2","European","Europe","English","Disneyland","CuSO4","CuS","CuO","CuCl2","Cu3P","Cu2S","Cu2O","Cu(OH)2","Cu(NO3)2","Cu","CsOH","Cs","CrCl3","Cr2O3","Cr2(SO4)3","Cr(MnO4)2","Cr","Confucian","CoSO4","Cl2","Chinese","China","Chicago","Celsius","Canada","CaSiO3","CaSO4","CaSO3","CaS5","CaS2O3","CaO","CaF2","CaCl2","CaCO3","CaC2","Ca3(PO4)2","Ca(OH)2","Ca(HSO3)2","Ca(HCO3)2","Ca(H2PO4)2","Ca(ClO)2","Ca(CN)2","Ca","CS2","CO2","CO","CHCl3","CH4","CH3OH","CH3Cl","CH3COONa","CH3COONH4","CH3COOH","CH3COOCH3","CH3COOC2H5","CH3CHO","CH3CH2OSO3H","CH3CH2OH","CH3CH2Br","CH2Cl2","CF2Cl2","CCl4","C6H6","C6H5SO3H","C6H5ONa","C6H5OH","C6H5NO2","C6H5Cl","C6H5Br","C6H12","C2H6","C2H5ONa","C2H5ONO2","C2H5OH","C2H5OC2H5","C2H4","C2H2","C(C(C(C(CH3)3)3)3)4","C","Brazilian","BrCl","Br2","Boston","Bible","Bi2(SO4)3","Beijing","BaSO4","BaCl2","BaCO3","Ba(OH)2","Ba(NO3)2","Ba","B10H12CNH3","Australian","Australia","August","Asian","Asia","AsH3","April","American","America","Amazon","AlCl3","Al2Si2O5(OH)4","Al2S3","Al2O3","Al2(SO4)3","Al(OH)3","Al(NO3)3","Al","AgOH","AgNO3","AgI","AgCl","AgBr","Ag3AsO4","Ag(NH3)2OH","Ag","African","Africa","Fe2SiO4","O2","Hg(NO3)2","Fe2O3","Cu","KMnO4","NaBH4","NH3","H2SO4","H2O","FeCl3","Fe3O4","SiH4","Na2SO4","H2SO4","H2S","GeS2","GeS","FeSO4","CuSO4","H2SO4","Te","O2","NaOH","NaHTe","NaBr","NH3","Mg","HCl","H2S","H2O","FeO","Cl2","CO2","Br2","AlCl3","Al(OH)3","Al","H2O","O2","MnSO4","NaCN","Mg2SiO4","H2O","H2O","H2","H2O","NaCl","Mg3Si2O5(OH)4","H2","K2SO4","H2O2","SiO2","Si","NaOH","HF","FeO","CaSiO3","(NH4)2SO4","(CH3COO)2Pb","(C2H5O)3Al","(C2H5O)2Mg",
};
static string similarWords[] = {
	"17iIJjLl",
	"2zZ",
	"38B",
	"4q7",
	"5SsrR",
	"6b",
	"9qpPy",
	"0oOD",
	"Mm",
	"uUVvwW",
};
HashNode2::HashNode2() { Exist = 0; }
HashNode1::HashNode1() { Exist = 0; }
HashNode0::HashNode0() { Exist = 0; }
int char2int(char c) {
	if ('0' <= c && c <= '9')return c - '0';
	else if ('A' <= c && c <= 'Z')return c - 'A' + 10;
	else if ('a' <= c && c <= 'z')return c - 'a' + 36;
	else if (c == '(')return 62;
	else if (c == ')')return 63;
	return -1;
}
char int2char(int i) {
	if (0 <= i && i <= 9)return i + '0';
	else if (i <= 35)return i + 'A' - 10;
	else if (i <= 61)return i + 'a' - 36;
	else if (i == 62)return '(';
	else if (i == 63)return ')';
	else return '\0';
}
string DCgetAllNext(string _prefix) {
	string res, res2;
	int len = _prefix.length();
	if (len == 0) {
		res = "";
	}
	else if (len == 1) {
		HashNode0& node0 = hashnode0[char2int(_prefix[0])];
		if (node0.Exist == 0)res = "";
		else {
			for (int i = 0; i < SUM_OF_KEY_CHAR; i++)
				if (node0.hashnode1[i].Exist)
					res += int2char(i);
		}
	}
	else if (len == 2) {
		HashNode0& node0 = hashnode0[char2int(_prefix[0])];
		HashNode1& node1 = node0.hashnode1[char2int(_prefix[1])];
		for (int i = 0; i < SUM_OF_KEY_CHAR; i++)
			if (node1.hashnode2[i].Exist)
				res += int2char(i);
	}
	else {
		HashNode0& node0 = hashnode0[char2int(_prefix[0])];
		HashNode1& node1 = node0.hashnode1[char2int(_prefix[1])];
		HashNode2& node2 = node1.hashnode2[char2int(_prefix[2])];
		size_t nSize = node2.txt.size(); size_t pos = 0;
		//cout << _prefix << endl;
		_prefix.erase(0, 3);
		//cout << _prefix << endl;
		string mark = "#" + _prefix;
		while (1) {
			pos = node2.txt.find(mark, pos);
			if (pos == std::string::npos)break;
			else if (node2.txt[pos + len - 2] != '#')res += node2.txt[pos + len - 2];
			pos++;
		}
	}
	if (res.length() <= 1)res2 = res;
	else {
		char lastc = res[0];
		for (int i = 1; i < res.length(); i++) {
			if (lastc != res[i]) {
				res2 += lastc; lastc = res[i];
			}
		}res2 += lastc;
	}
	return res2;
}
void DCinsert(string _word) {
	int len = _word.length();
	if (len == 0) return;
	else if (len == 1) {
		hashnode0[char2int(_word[0])].Exist = 1;
	}
	else if (len == 2) {
		HashNode0& node0 = hashnode0[char2int(_word[0])];
		node0.Exist = 1;
		node0.hashnode1[char2int(_word[1])].Exist = 1;
	}
	else {
		HashNode0& node0 = hashnode0[char2int(_word[0])];
		node0.Exist = 1;
		HashNode1& node1 = node0.hashnode1[char2int(_word[1])];
		node1.Exist = 1;
		HashNode2& node2 = node1.hashnode2[char2int(_word[2])];
		node2.Exist = 1;
		node2.txt += "#";
		for (int i = 3; i < len; i++)
			node2.txt += _word[i];
		//cout << _word[0] << _word[1] << _word[2] << node2.txt; system("pause");
	}
}
void DCinit() {
	for (int i = 0; i < SUM_OF_DICTIONARY_WORDS; i++)
		DCinsert(myDearWords[i]);
}
void DCdisplayAll() {
	for (int i = 0; i < SUM_OF_KEY_CHAR; i++) {
		HashNode0& node0 = hashnode0[i];
		if (node0.Exist) {
			for (int j = 0; j < SUM_OF_KEY_CHAR; j++) {
				HashNode1& node1 = node0.hashnode1[j];
				if (node1.Exist) {
					for (int k = 0; k < SUM_OF_KEY_CHAR; k++) {
						HashNode2& node2 = node1.hashnode2[k];
						if (node2.Exist) {
							cout << int2char(i) << int2char(j) << int2char(k);
							cout << node2.txt << endl;
						}
					}
				}
			}
		}
	}
}
int DCmakeChoice(string _prefix, vector<float>& weight) {
	int res = char2int('H'); char tmp;
	//std::cout << "目标前缀为：" << _prefix << endl;
	string possiblenext = DCgetAllNext(_prefix);//收集前缀_prefix所有可能的下一个字符
	//std::cout << "备选字母为：" << possiblenext << endl;
	for (int i = 0; i < weight.size(); i++) {	//收集模型计算出的所有概率大于0.1的字符
		if (weight[i] > 0.05) {
			tmp = int2char(i);
			if (possiblenext.find(tmp) != string::npos && weight[i] > weight[res])
				res = i;
		}
	}
	if (res == char2int('H')) {
		res = 0;
		for (int j = 0; j < weight.size(); j++)
			if (weight[res] < weight[j])
				res = j;
	}
	if (_prefix.length() == 0 && 36 <= res && res <= 61)
		res -= 26;
	return res;
}
